#+TITLE: Emacs Configuration
#+AUTHOR: Ankur Sethi <contact@ankursethi.in>

* Paperwork

File header.

#+BEGIN_SRC emacs-lisp
  ;;; README.el --- Literate configuration for Emacs -*- lexical-binding: t -*-

  ;;; Commentary:
  ;; My personal initialization file for Emacs.

  ;;; Code:
#+END_SRC

Set encoding to UTF-8.

#+BEGIN_SRC emacs-lisp
  (prefer-coding-system 'utf-8)
#+END_SRC

Personal information.

#+BEGIN_SRC emacs-lisp
  (setq user-full-name "Ankur Sethi"
        user-mail-address "contact@ankursethi.com")
#+END_SRC

Platform specific variables.

#+BEGIN_SRC emacs-lisp
  (defvar s3thi/is-a-mac (eq system-type 'darwin))
  (defvar s3thi/is-a-pc (eq system-type 'windows-nt))
  (defvar s3thi/is-a-penguin (eq system-type 'gnu/linux))
#+END_SRC

* User interface

** General UI enhancements

Remove UI elements we don't like.

#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (setq inhibit-startup-screen t)
  (setq initial-scratch-message nil)
  (setq ring-bell-function 'ignore)
#+END_SRC

And add UI elements that are nice to have.

#+BEGIN_SRC emacs-lisp
  (column-number-mode 1)
  (show-paren-mode)
  (setq confirm-kill-emacs #'yes-or-no-p)
  #+END_SRC

Enable smooth scrolling.

#+BEGIN_SRC emacs-lisp
  (pixel-scroll-precision-mode 1)
#+END_SRC

Allow resizing the frame by pixels instead of rounding the frame size to characters. This prevents an irritating situation on macOS where sometimes there's a bit of space left between the bottom of the Emacs frame and the bottom of the screen when maximizing Emacs using an external window manager.

#+BEGIN_SRC emacs-lisp
  (setq frame-resize-pixelwise t)
#+END_SRC

Set a nice font. The font size will have to be different across
platforms, so we check the OS we're running on before setting it.

#+BEGIN_SRC emacs-lisp
  (when s3thi/is-a-mac
    (set-face-attribute 'default nil
                        :family "Berkeley Mono Variable"
                        :height 160)
    (set-face-attribute 'variable-pitch nil
                        :family "Baskerville"
                        :height 170))
#+END_SRC

Maximize the Emacs frame on startup. To start every new frame maximized instead of just the first frame, you can add the following options to =default-frame-alist= instead of =initial-frame-alist=. Additionally, it's possible to toggle the maximized status of an Emacs frame by calling =toggle-frame-maximized=, which is bound to =M-<f10>= by default.

#+BEGIN_SRC emacs-lisp :tangle no
  (add-to-list 'initial-frame-alist '(fullscreen . maximized))
#+END_SRC

=scroll-conservatively= specifies the number of lines to scroll the
buffer in order to bring the cursor back on the screen when it moves
off-screen. If moving that much doesn't bring the cursor back, Emacs
will scroll the buffer by as many lines as it takes to bring the
cursor to the exact center of the screen.

This behavior is irritating and jarring, causing huge jumps as you
move around a file. Luckily, setting this variable to a number larger
than 100 tells Emacs to /never/ scroll by large amounts, and instead
scroll the screen /just enough/ to keep the cursor visible.

In summary, setting =scroll-conservatively= to 101 will make Emacs
behave like every other text editor on the planet.

#+BEGIN_SRC emacs-lisp
    (setq scroll-conservatively 101)
#+END_SRC

=scroll-margin= specifies the number of lines of margin at the top or
bottom of the window. As soon as the cursor gets closer than this to the
top of or bottom of a window, Emacs will start scrolling.

#+BEGIN_SRC emacs-lisp
  (setq scroll-margin 5)
#+END_SRC

Show total number of matches while searching:

#+BEGIN_SRC emacs-lisp
  (setq-default isearch-lazy-count t)
#+END_SRC

=undo-tree= lets me browse the Emacs undo history visually.

#+BEGIN_SRC emacs-lisp
  (use-package undo-tree
    :ensure t
    :diminish undo-tree-mode
    :config
    (global-undo-tree-mode)
    (setq undo-tree-visualizer-timestamps t)
    (setq undo-tree-visualizer-diff t)
    (setq undo-tree-history-directory-alist
          `(("." . ,(concat user-emacs-directory "undo-tree/")))))
#+END_SRC

=browse-kill-ring= lets me browse the kill ring visually.

#+BEGIN_SRC emacs-lisp
  (use-package browse-kill-ring
    :ensure t)
#+END_SRC

=which-key= displays helpful suggestions in the minibuffer when you hit
the first part of a long keychord.

#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :diminish
    :config
    (which-key-mode 1))
#+END_SRC

=diminish= prevents the modeline from getting polluted when too many
modes are enabled for a single buffer. This conveniently integrates with
use-package.

#+BEGIN_SRC emacs-lisp
  (use-package diminish
    :ensure t)
#+END_SRC

** Minibuffer completion

Use =vertico= as the completion UI.

#+BEGIN_SRC emacs-lisp
  (use-package vertico
    :ensure t
    :init
    (vertico-mode))
#+END_SRC

Use =savehist= to save minibuffer history.

#+BEGIN_SRC emacs-lisp
  (use-package savehist
    :ensure t
    :init
    (savehist-mode))
#+END_SRC

Use =orderless= to filter completions.

#+BEGIN_SRC emacs-lisp
  (use-package orderless
    :ensure t
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+END_SRC

Enable annotations in the minibuffer using =marginalia=.

#+BEGIN_SRC emacs-lisp
  (use-package marginalia
    :ensure t
    ;; Bind `marginalia-cycle' locally in the minibuffer.  To make the binding
    ;; available in the *Completions* buffer, add it to the
    ;; `completion-list-mode-map'.
    :bind (:map minibuffer-local-map
                ("M-A" . marginalia-cycle))
    :init
    (marginalia-mode))
#+END_SRC

** Themes

Let's install some Doom Emacs themes!

#+BEGIN_SRC emacs-lisp
  (use-package doom-themes
    :ensure t
    :custom
    ;; Global settings (defaults)
    (doom-themes-enable-bold t)   ; if nil, bold is universally disabled
    (doom-themes-enable-italic t) ; if nil, italics is universally disabled
    ;; for treemacs users
    (doom-themes-treemacs-theme "doom-atom") ; use "doom-colors" for less minimal icon theme
    :config
    ;; Enable flashing mode-line on errors
    (doom-themes-visual-bell-config)
    ;; Enable custom neotree theme (nerd-icons must be installed!)
    (doom-themes-neotree-config)
    ;; or for treemacs users
    (doom-themes-treemacs-config)
    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config))
#+END_SRC

Settings for the included =modus= themes.

#+BEGIN_SRC emacs-lisp
  (setq modus-themes-org-blocks 'gray-background)
#+END_SRC

Load a theme.

#+BEGIN_SRC emacs-lisp
  (load-theme 'doom-one t)
#+END_SRC

* Files and directories

Store configuration created by custom in a separate file.

#+BEGIN_SRC emacs-lisp
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file)
    (load-file custom-file))
#+END_SRC

Don't create garbage files.

#+BEGIN_SRC emacs-lisp
  (setq-default create-lockfiles nil)
  (setq-default make-backup-files nil)
#+END_SRC

Don't pollute the current directory with auto-save files. Instead, put them all in one place.

#+BEGIN_SRC emacs-lisp
  (let ((auto-save-dir (expand-file-name "auto-save/" user-emacs-directory)))
    (unless (file-exists-p auto-save-dir)
      (make-directory auto-save-dir t))
    (setq auto-save-file-name-transforms
          `((".*" ,auto-save-dir t))))
#+END_SRC

Turn on =auto-revert-mode= for all files. This will automatically reload
files from disk every time they're changed by another from outside
Emacs.

Also ensure that Dired, VCS, etc. buffers are also auto reverted.

#+BEGIN_SRC emacs-lisp
  (setq global-auto-revert-non-file-buffers t)
  (global-auto-revert-mode 1)
#+END_SRC

Save place in files.

#+BEGIN_SRC emacs-lisp
  (save-place-mode 1)
#+END_SRC

If a read-only file is opened, use =view-mode= instead of the regular
mode. This ensures you can't accidentally change or overwrite the
file.

#+BEGIN_SRC emacs-lisp
  (setq view-read-only t)
#+END_SRC

Use =ripgrep= for searching.

#+BEGIN_SRC emacs-lisp
  (use-package rg
    :ensure t
    :config
    (rg-enable-default-bindings))
#+END_SRC

* Text editing

Enable useful text editing commands that are disabled by default.

#+BEGIN_SRC emacs-lisp
  (put 'upcase-region 'disabled nil)
  (put 'downcase-region 'disabled nil)
  (put 'scroll-left 'disabled nil)
#+END_SRC

Make sure sentences end with single spaces, not double spaces. This
makes functions that operate on prose behave better (such as those in
=org-mode= and =markdown-mode=).

#+BEGIN_SRC emacs-lisp
  (setq sentence-end-double-space nil)
#+END_SRC

Always use spaces for indentation. Affects all modes, unless we
override it later. The only programming language I've used that
mandates the use of tabs rather than spaces is Go, so it's safe to set
this here and override it for Go if I ever write it again.

#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC

In modes where we are forced to use tabs, set the tab width to 4.

#+BEGIN_SRC emacs-lisp
  (setq-default tab-width 4)
#+END_SRC

Set =fill-column= manually, to make sure it's always what I expect.

#+BEGIN_SRC emacs-lisp
  (setq-default fill-column 80)
#+END_SRC

If there is some text already present in the system clipboard when we
run an Emacs command that kills text, make sure that is preserved by
pushing it into the kill ring.

Since we've configured Emacs to put text into the system clipboard --
in addition to the kill ring -- when we kill it, this setting ensures
that we never lose whatever might have already been in the clipboard
when we perform a kill operation. Not always useful, but a nice to
have.

#+BEGIN_SRC emacs-lisp
  (setq save-interprogram-paste-before-kill t)
#+END_SRC

Make word movement commands take CamelCase words into account. Also
make sure we diminish this, otherwise it shows up as an irritating
little comma in the modeline.

#+BEGIN_SRC emacs-lisp
  (use-package subword
    :diminish
    :config
    (global-subword-mode 1))
#+END_SRC

Snippets are useful, right?

#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :ensure t
    :diminish yas-minor-mode
    :config
    (yas-global-mode 1)
    (define-key yas-minor-mode-map (kbd "<tab>") nil)
    (define-key yas-minor-mode-map (kbd "TAB") nil)
    (define-key yas-minor-mode-map (kbd "C-c y") #'yas-expand))
#+END_SRC

Sometimes it's useful to "unfill" paragraphs.

#+BEGIN_SRC emacs-lisp
  (use-package unfill
    :ensure t)
#+END_SRC

* Improvements to writing prose

Add =visual-fill-column= to limit text width in certain modes.

#+BEGIN_SRC emacs-lisp
  (use-package visual-fill-column
    :ensure t
    :init
    (advice-add 'text-scale-adjust :after #'visual-fill-column-adjust)
    (global-set-key (kbd "<f12>") #'visual-fill-column-toggle-center-text))
#+END_SRC

* Org

Note that =visual-wrap-prefix-mode=, which we use for Markdown, doesn't work well with =org-mode= when =org-indent-mode= is also turned on. If you're running into weird issues, it's probably because of that.

#+BEGIN_SRC emacs-lisp
  (use-package org
    :hook ((org-mode . org-indent-mode)
           (org-mode . visual-fill-column-mode)
           (org-mode . visual-line-mode))
    :config
    (setq org-startup-folded 'content)
    (setq org-M-RET-may-split-line '((headline . nil)))
    (setq org-list-demote-modify-bullet
          '(("-" . "+") ("+" . "*") ("*" . "-"))))
#+END_SRC

* Markdown

#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :ensure t
    :hook ((markdown-mode . visual-line-mode)
           (markdown-mode . visual-fill-column-mode)
           (markdown-mode . visual-wrap-prefix-mode))
    :mode (("\\.md\\'" . markdown-mode)
           ("\\.markdown\\'" . markdown-mode))
  :init
  (setq markdown-header-scaling t)
  (setq markdown-header-scaling-values '(1.4 1.3 1.2 1.1 1.0 1.0))
  (setq markdown-hide-urls t))
#+END_SRC

* Version control

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t)
#+END_SRC

* Programming

** Flycheck

#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t
    :init (global-flycheck-mode))
#+END_SRC

* Additional key bindings

Disable C-z to suspend in GUI Emacs. By default, hitting C-z in GUI
Emacs will minimize the editor, which is very annoying. This disables
that behavior. On terminal Emacs, this will still allow us to suspend
the editor and go back to our shell.

#+BEGIN_SRC emacs-lisp
  (when window-system
    (global-unset-key (kbd "C-z")))
#+END_SRC

Convenient for editing this configuration file.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c i") (lambda ()
                                  (interactive)
                                  (find-file "~/.emacs.d/README.org")))
#+END_SRC

This one is very useful for the way I work:

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-o") #'other-window)
#+END_SRC

* Miscellaneous

=crux= contains a ton of useful Emacs Lisp functions that I'd have to
write myself otherwise.

#+BEGIN_SRC emacs-lisp
  (use-package crux
    :ensure t
    :bind (("C-c d" . #'crux-duplicate-current-line-or-region)
           ("C-c r" . #'crux-transpose-windows)))
#+END_SRC

* Claude suggestions

** Performance Optimizations

*** early-init.el Missing Essential Optimizations

early-init.el:20 - Missing essential early-init optimizations that should be added:

#+BEGIN_SRC emacs-lisp :tangle no
  ;; Add to early-init.el:
  (setq package-enable-at-startup nil)  ;; Prevent double package initialization

  ;; Disable GUI elements before they're loaded to speed up startup
  (push '(menu-bar-lines . 0) default-frame-alist)
  (push '(tool-bar-lines . 0) default-frame-alist)
  (push '(vertical-scroll-bars) default-frame-alist)

  ;; Adjust GC threshold during startup
  (setq gc-cons-threshold most-positive-fixnum)
  (add-hook 'emacs-startup-hook
            (lambda ()
              (setq gc-cons-threshold (* 16 1024 1024))))
#+END_SRC

*** Redundant Package Initialization

init.el:14 - The =package-initialize= call is redundant in Emacs 27+ (it
happens automatically).

** Undo-tree Concerns

README.org:135-143 - =undo-tree= is deprecated/unmaintained and can cause corruption issues. Consider switching to =vundo= (visual undo):

#+BEGIN_SRC emacs-lisp :tangle no
  ;; Alternative to undo-tree:
  (use-package vundo
    :ensure t
    :bind (("C-x u" . vundo))
    :config
    (setq vundo-glyph-alist vundo-unicode-symbols))
#+END_SRC

** Missing Useful Configurations

*** Recent Files Mode

No recent files tracking. Add:

#+BEGIN_SRC emacs-lisp :tangle no
  (use-package recentf
    :config
    (setq recentf-max-saved-items 100)
    (setq recentf-max-menu-items 15)
    (setq recentf-exclude '("/tmp/" "/ssh:" "COMMIT_EDITMSG"))
    (recentf-mode 1))
#+END_SRC

*** Winner Mode (Window Configuration Undo)

You use =other-window= but might benefit from =winner-mode=:

#+BEGIN_SRC emacs-lisp :tangle no
  (use-package winner
    :config
    (winner-mode 1))
  ;; Use C-c <left> and C-c <right> to undo/redo window configuration changes
#+END_SRC

*** Eldoc Configuration

Useful for showing documentation in minibuffer, especially with LSP:

#+BEGIN_SRC emacs-lisp :tangle no
  (use-package eldoc
    :diminish eldoc-mode
    :config
    (global-eldoc-mode 1)
    (setq eldoc-idle-delay 0.2))
#+END_SRC

** Vertico Enhancements

README.org:178-181 - Basic vertico setup. Consider adding consult for
enhanced search/navigation:

#+BEGIN_SRC emacs-lisp :tangle no
  (use-package consult
    :ensure t
    :bind (("C-x b" . consult-buffer)
           ("C-x 4 b" . consult-buffer-other-window)
           ("C-x 5 b" . consult-buffer-other-frame)
           ("C-x r b" . consult-bookmark)
           ("M-y" . consult-yank-pop)
           ("M-g g" . consult-goto-line)
           ("M-g M-g" . consult-goto-line)
           ("M-g o" . consult-outline)
           ("M-g m" . consult-mark)
           ("M-g k" . consult-global-mark)
           ("M-g i" . consult-imenu)
           ("M-s d" . consult-find)
           ("M-s D" . consult-locate)
           ("M-s g" . consult-grep)
           ("M-s G" . consult-git-grep)
           ("M-s r" . consult-ripgrep)
           ("M-s l" . consult-line)
           ("M-s L" . consult-line-multi)
           ("M-s m" . consult-multi-occur)
           ("M-s k" . consult-keep-lines)
           ("M-s u" . consult-focus-lines)))

  ;; Enable vertico-multiform for different completion styles
  (use-package vertico-multiform
    :after vertico
    :config
    (vertico-multiform-mode))
#+END_SRC

** Custom File Directory Issue

README.org:248-250 - Consider creating the file if it doesn't exist:

#+BEGIN_SRC emacs-lisp :tangle no
  ;; Ensure custom file exists before loading:
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (unless (file-exists-p custom-file)
    (write-region "" nil custom-file))
  (load-file custom-file)
#+END_SRC

* That's all, folks!

#+BEGIN_SRC emacs-lisp
  ;;; README.el ends here.
#+END_SRC
