(use-package elfeed
  :ensure t)

(setq elfeed-feeds
      '("https://ankursethi.in/feed/"
        "https://bradfrost.com/feed/"
        "https://fogknife.com/atom.xml"
        "https://macwright.com/rss.xml"
        "https://shapeof.com/rss.xml"
        "https://notes.abhinavsarkar.net/feed.atom"
        "https://arunraghavan.net/feed/"
        "https://eli.thegreenplace.net/feeds/all.atom.xml"
        "https://markboulton.co.uk/journal/feed"
        "https://prtksxna.com/feed/"
        "http://blog.fogus.me/feed/"
        "https://alicebartlett.co.uk/feed.xml"
        "http://www.zeldman.com/rss/"
        "https://styledeficit.tumblr.com/rss"
        "https://fberriman.com/feed/"
        "https://anti-mega.com/again/feed/"
        "https://natbuckley.co.uk/atom.xml"
        "https://www.gyford.com/phil/writing/feeds/posts/rss/"
        "https://maya.land/feed.xml"
        "https://lexi-lambda.github.io/feeds/all.atom.xml"
        "https://lucumr.pocoo.org/feed.atom"
        "https://anaulin.org/blog/index.xml"
        "https://cadence.moe/blog/rss.xml?limit=30"
        "https://emmas.site/blog/atom.xml"
        "https://jvns.ca/atom.xml"
        "https://nora.codes/index.xml"
        "https://blog.m-ou.se/index.xml"
        "http://brooker.co.za/blog/rss.xml"
        "https://nataliaantonova.substack.com/feed"
        "https://ohhelloana.blog/feed.xml"
        "https://www.labbott.name/feed.xml"
        "https://beepb00p.xyz/feed.html"
        "https://dammit.nl/feeds/all.atom.xml"
        "https://linuxwit.ch/feed.xml"
        "https://matt.sh/.rss"
        "https://ameyama.com/blog/rss.xml"
        "https://captainawkward.com/feed/"
        "https://twelvety.micro.blog/feed.xml"
        "https://winnielim.org/feed"
        "https://www.kickscondor.com/feed.xml"
        "https://mara.substack.com/feed.xml"
        "https://nadiaeghbal.com/feed.xml"
        "http://jennytrout.com/?feed=rss2"
        "https://eev.ee/feeds/blog.atom.xml"
        "https://cestlaz.github.io/rss.xml"
        "http://usethe.computer/rss.xml"
        "https://emacsnyc.org/atom.xml"))

(provide 'init-elfeed)
